import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: 'tutorials'},
    {type: 'autogenerated', dirName: 'how-to'},
    {type: 'autogenerated', dirName: 'explanations'},
    {type: 'autogenerated', dirName: 'reference'},
  ],
};

export default sidebars;
